import { useEffect, useRef } from 'react'
import { formatDate } from '../lib/format'
import type { Website } from '../types'
import { ArrowUpRight, CloseIcon } from './Icons'
import { SiteFavicon } from './SiteFavicon'

interface Props {
  site: Website | null
  onClose: () => void
}

/** Modal built on the native <dialog>: focus trap, Escape and focus restoration come from the browser. */
export function DetailsDialog({ site, onClose }: Props) {
  const ref = useRef<HTMLDialogElement>(null)

  useEffect(() => {
    const dialog = ref.current
    if (!dialog) return
    if (site && !dialog.open) dialog.showModal()
    if (!site && dialog.open) dialog.close()
  }, [site])

  const facts: { label: string; value: string }[] = []
  if (site) {
    if (site.authority !== null) facts.push({ label: 'Domain Rating', value: `${site.authority} / 100` })
    if (site.liveSince) facts.push({ label: 'First confirmed live', value: formatDate(site.liveSince) })
    if (site.firstSeen) facts.push({ label: 'First discovered', value: formatDate(site.firstSeen) })
    if (site.builtWith) facts.push({ label: 'Built with', value: site.builtWith })
  }

  return (
    <dialog
      ref={ref}
      className="dialog"
      aria-labelledby="dialog-title"
      onClose={onClose}
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose()
      }}
    >
      {site && (
        <div className="dialog-panel">
          <div className="dialog-head">
            <SiteFavicon domain={site.domain} size={48} />
            <div className="dialog-id">
              <h2 id="dialog-title">{site.title}</h2>
              <p className="card-domain">{site.domain}</p>
            </div>
            <button type="button" className="icon-btn dialog-close" onClick={onClose} aria-label="Close details">
              <CloseIcon />
            </button>
          </div>

          <div className="dialog-body" tabIndex={0} role="region" aria-labelledby="dialog-title">
            {site.categories.length > 0 && (
              <ul className="tags" aria-label="AI categories">
                {site.categories.map((c) => (
                  <li key={c} className="tag">
                    {c}
                  </li>
                ))}
              </ul>
            )}

            {site.summary ? (
              <p className="dialog-summary">{site.summary}</p>
            ) : (
              <p className="dialog-summary muted">No description available for this website.</p>
            )}

            {facts.length > 0 && (
              <dl className="facts">
                {facts.map((f) => (
                  <div key={f.label}>
                    <dt>{f.label}</dt>
                    <dd>{f.value}</dd>
                  </div>
                ))}
              </dl>
            )}

            <p className="dialog-note">
              Summary generated by FreeSERP from the site’s homepage. Always verify before you rely on a tool.
            </p>
          </div>

          <div className="dialog-actions">
            <a className="btn btn-primary" href={site.url} target="_blank" rel="noopener noreferrer">
              Visit website
              <ArrowUpRight width={16} height={16} />
              <span className="sr-only"> (opens in a new tab)</span>
            </a>
          </div>
        </div>
      )}
    </dialog>
  )
}
